<a href="https://colab.research.google.com/github/sebasGarciaC/DS_Sebastian/blob/main/Matriz_con_Numpy_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
A = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12],[13,14,15,16,17,18],[19,20,21,22,23,24],[25,26,27,28,29,30],[31,32,33,34,35,36]])
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
A [5,5] = 36
A

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24],
       [25, 26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35, 36]])

In [ ]:
A[2]=[ 7,  8,  9, 10, 11, 12]

In [ ]:
A[]

array([13, 14, 15, 16, 17, 18])

In [ ]:
ced =[1,2,3]
nom = ['a','b','c']
edad = [4,5,6]
per ={}
for i in range(len(ced)):
  per[ced[i]] = {'nombre :':nom[i], 'edad :': edad[i]}
  print(ced[i],nom[i],edad[i])
per

1 a 4
2 b 5
3 c 6


{1: {'nombre :': 'a', 'edad :': 4},
 2: {'nombre :': 'b', 'edad :': 5},
 3: {'nombre :': 'c', 'edad :': 6}}